spring.application.name=diabetesReportService

server.port=8083

logging.config=classpath:log4j2-spring.xml

gateway.url=${GATEWAY_URL:http://localhost:8080}
gateway.username=${GATEWAY_USERNAME:user}
gateway.password=${GATEWAY_PASSWORD:password}
