
services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_DATABASE: patientdb
      MYSQL_USER: patientuser
      MYSQL_PASSWORD: patientpass
      MYSQL_ROOT_PASSWORD: rootpass
    ports:
      - "3307:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql-init:/docker-entrypoint-initdb.d
    networks:
      - medilabo_net
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  patientservice:
    image: patientservice:latest
    build:
      context: ./patientService
    container_name: patient_service
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/patientdb
      SPRING_DATASOURCE_USERNAME: patientuser
      SPRING_DATASOURCE_PASSWORD: patientpass
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - medilabo_net

  gatewayservice:
    build:
      context: ./gatewayService
    ports:
      - "8080:8080"
    depends_on:
      - patientservice
      - notesservice
      - diabetesreportservice
    networks:
      - medilabo_net

  mongodb:
    image: mongo:6.0
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db
      - ./mongodb-init/init-mongodb.js:/docker-entrypoint-initdb.d/init-mongodb.js:ro
    networks:
      - medilabo_net

  notesservice:
    build:
      context: ./notesService
    ports:
      - "8082:8082"
    depends_on:
      mongodb:
        condition: service_started
    networks:
      - medilabo_net

  diabetesreportservice:
    build:
      context: ./diabetesReportService
    ports:
      - "8083:8083"
    environment:
      - GATEWAY_URL=http://gatewayservice:8080
      - GATEWAY_USERNAME=user
      - GATEWAY_PASSWORD=password
    networks:
      - medilabo_net


  frontend:
    build:
      context: ./frontend
    container_name: frontend
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    command: ["npm", "run", "dev", "--", "--host"]
    networks:
      - medilabo_net
    depends_on:
      - gatewayservice

volumes:
  mysql_data:
  mongodb_data:

networks:
  medilabo_net:
