spring.application.name=notesService

server.port=8082

# MongoDB configuration
spring.data.mongodb.uri=mongodb://mongodb:27017/notesdb

# Local MongoDB configuration (uncomment if running locally)
#spring.data.mongodb.uri=mongodb://localhost:27017/notesdb

logging.config=classpath:log4j2-spring.xml