server:
  port: 8080  # Port de ta gateway

spring:
  application:
    name: gateway-service

  cloud:
    gateway:
      routes:
        - id: patient-service
          uri: http://localhost:8081
          predicates:
            - Path=/api/patients/**
          filters:
            - StripPrefix=1

        - id: notes-service
          uri: http://localhost:8082
          predicates:
            - Path=/api/notes/**
          filters:
            - StripPrefix=1